updates:
- commit-message:
    prefix: "chore(deps)"
  directory: /
  ignore:
  - dependency-name: black
  - dependency-name: isort
  - dependency-name: mypy
  package-ecosystem: pip
  schedule:
    interval: daily
- commit-message:
    prefix: "chore(deps)"
  directory: /
  package-ecosystem: docker
  schedule:
    interval: daily
version: 2
