updates:
- commit-message:
    prefix: "chore"
  directory: /
  package-ecosystem: pip
  schedule:
    interval: daily
- commit-message:
    prefix: "chore"
  directory: /
  package-ecosystem: docker
  schedule:
    interval: daily
- commit-message:
    prefix: "chore"
  directory: /docs
  package-ecosystem: pip
  schedule:
    interval: daily
version: 2
