updates:
- directory: /
  ignore:
  - dependency-name: black
  - dependency-name: isort
  - dependency-name: mypy
  package-ecosystem: pip
  schedule:
    interval: daily
- directory: /
  package-ecosystem: docker
  schedule:
    interval: daily
version: 2
