on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Test and build main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v5
      - run: poetry install
      - run: make lint
      - run: make test
      - name: Build Docker image
        run: make docker_build
      - name: Configure Docker to use env credentials reader
        run: |
          mkdir -p "$HOME/.docker"
          echo '{"credsStore": "env"}' > "$HOME/.docker/config.json"
      - name: Make Docker env credentials reader available in PATH
        run: |
          echo "$GITHUB_WORKSPACE/build/docker" >> $GITHUB_PATH
      - name: Push Docker image
        env:
          DOCKER_REGISTRY: https://index.docker.io/v1/
          DOCKER_CREDS_USR: wandhydrant
          DOCKER_CREDS_PSW: ${{ secrets.DOCKER_CREDS_PSW }}
          RCMT_VERSION: main
        run: make docker_push
