on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: Gr1N/setup-poetry@v5
      - run: poetry install
      - run: make lint
      - run: make test
